// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace AplicacionWeb
{
    public partial class ModeloCalendario
    {
        /// <summary>
        /// model input class for ModeloCalendario.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Id")]
            public float Id { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"PromedioPromocionAlumno")]
            public float PromedioPromocionAlumno { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"CantMateriasElegidas")]
            public float CantMateriasElegidas { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"MenorPromedioPromocionMateria")]
            public float MenorPromedioPromocionMateria { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"IdMateria")]
            public float IdMateria { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"PromedioPromocionMateria")]
            public float PromedioPromocionMateria { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Dia")]
            public string Dia { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"InicioMayorTiempoLibre")]
            public float InicioMayorTiempoLibre { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"FinMayorTiempoLibre")]
            public float FinMayorTiempoLibre { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"InicioPrediccionHorarioEstudio")]
            public float InicioPrediccionHorarioEstudio { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"FinPrediccionHorarioEstudio")]
            public float FinPrediccionHorarioEstudio { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ModeloCalendario.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Id")]
            public float Id { get; set; }

            [ColumnName(@"PromedioPromocionAlumno")]
            public float PromedioPromocionAlumno { get; set; }

            [ColumnName(@"CantMateriasElegidas")]
            public float CantMateriasElegidas { get; set; }

            [ColumnName(@"MenorPromedioPromocionMateria")]
            public float MenorPromedioPromocionMateria { get; set; }

            [ColumnName(@"IdMateria")]
            public float IdMateria { get; set; }

            [ColumnName(@"PromedioPromocionMateria")]
            public float PromedioPromocionMateria { get; set; }

            [ColumnName(@"Dia")]
            public float[] Dia { get; set; }

            [ColumnName(@"InicioMayorTiempoLibre")]
            public float InicioMayorTiempoLibre { get; set; }

            [ColumnName(@"FinMayorTiempoLibre")]
            public float FinMayorTiempoLibre { get; set; }

            [ColumnName(@"InicioPrediccionHorarioEstudio")]
            public float InicioPrediccionHorarioEstudio { get; set; }

            [ColumnName(@"FinPrediccionHorarioEstudio")]
            public float FinPrediccionHorarioEstudio { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ModeloCalendario.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
